### PR TITLE
Ensure tags are synced to client before JEI loads

### LINKED ISSUE #2177: Tags used befor it was bound during client load connecting on server
When a player join a server tags and recipes are sent with two separates packet. JEI starts when the recipes packet is received (using `RecipesUpdatedEvent`).
If the tag packaet hasen't been received yet and a mod plugin uses tags an exception (`java.lang.IllegalStateException: Tag <tag> used before it was bound`) will be thrown.

It may also be the cause of https://github.com/mezz/JustEnoughItems/issues/2165

### PR DESCRIPTION
**Pull request by Alwinfy**
Hopefully fixes #2177, #2165

### CODE REVIEW

**Comment by Vazkii** [comment]
Tested it on my server, can confirm it works.

File: src/main/java/mezz/jei/startup/ClientLifecycleHandler.java [hunk 1]
```diff
@@ -89,43 +90,63 @@ public ClientLifecycleHandler(NetworkHandler networkHandler, Textures textures)
...
+				setupJEI();
+			}
+		});
+		// Listener for forge remote server
+		EventBusHelper.addListener(this, TagsUpdatedEvent.CustomTagTypes.class, event -> {
 			ClientPlayNetHandler connection = Minecraft.getInstance().getConnection();
-			if (connection != null) {
-				NetworkManager networkManager = connection.getNetworkManager();
-				worldConfig.syncWorldConfig(networkManager);
+			if (connection != null && !NetworkHooks.isVanillaConnection(connection.getNetworkManager()) && !Minecraft.getInstance().isIntegratedServerRunning()) {
```
Comment (mezz) [inline src/main/java/mezz/jei/startup/ClientLifecycleHandler.java]: To help clarify this logic, can you create a new enum and a helper function that returns `IntegratedVanillaServer`, `IntegratedForgeServer`, `RemoteVanillaServer`, or `RemoteForgeServer`? Then these conditions can just check using the enums.

**Review by mezz — CHANGES_REQUESTED** [review]
Thanks for contributing, this looks great!
I have a small request to clean up some of the logic, but otherwise looks good to me.

**Review by mezz — APPROVED** [review]
super clean 👌

**Comment by mezz** [comment]
@Vazkii can you test out this updated version? Then I can merge 👍

File: src/main/java/mezz/jei/startup/ClientLifecycleHandler.java [hunk 2]
```diff
@@ -139,4 +147,27 @@ private void onRecipesLoaded() {
...
+
+		private ServerType(boolean isVanilla, boolean isIntegrated, Class<? extends Event> listenerClass) {
+			this.isVanilla = isVanilla;
+			this.isIntegrated = isIntegrated;
+			this.listenerClass = listenerClass;
+		}
+
+		public boolean connected() {
+			ClientPlayNetHandler connection = Minecraft.getInstance().getConnection();
+			boolean isVanilla = connection != null && NetworkHooks.isVanillaConnection(connection.getNetworkManager());
```
Comment (pupnewfster) [inline src/main/java/mezz/jei/startup/ClientLifecycleHandler.java:168]: It probably doesn't really matter because most people should be on 1.16.5 now and at the very least 1.16.4, but realistically this PR due to using this helper method should have bumped the min forge version from 1.16.3-34.0.3 to 1.16.3-34.0.18

**Comment by Susanmsachs-commits** [comment]
@Alwinfy or @mezz how and where would I put in this code? I'm not tech savy but I really want to make JEI work for a server with my friends. Do I go in command prompt and copy the code; do I write it in notes; or do I configure an already made file of the server's code? Any advice or help would be greatly appreciated from anyone too.
